import { CardsProps } from "./cardsTypes";

export const data = [
  {
    id: 1091584,
    offer_type: "Survey",
    model: "Survey",
    name: "Trust Pilot Review",
    instructions: "Rate 5 stars and write good comment{No points}",
    description: "Rate 5 stars and write good comment {No points}",
    short_description: "Rate 5 stars and write good comment {No points}",
    disclaimer: "Rate 5 stars and write good comment {No points}",
    payout: "0.70",
    image: "https://cdn.trustpilot.net/brand-assets/4.3.0/logo-white.svg",
    countries: ["Ww"],
    goals: null,
    os: "web",
    incent: "0",
    url: "https://adspiritmedia.com/api/manual-offer/10000/1091584/ker00sama",
    reward: 350,
    favorite: 0,
  },
  {
    id: 433,
    offer_type: "CPI",
    model: "offer",
    name: "Research on Mobile EG",
    instructions: "Complete a survey and get rewarded",
    description: "Complete a survey and get rewarded",
    short_description:
      "Ολοκληρώστε την έρευνα και λάβετε το βραβείο σας\r\n(Complete Multiple Times Daily)",
    disclaimer:
      "Ολοκληρώστε την έρευνα και λάβετε το βραβείο σας\r\n(Complete Multiple Times Daily)",
    payout: "0.32",
    image:
      "https://s3.amazonaws.com/adscendmedia-image-storage/4970961-5148850.png",
    countries: ["EG"],
    goals: null,
    os: "web",
    incent: "1",
    url: "https://adspiritmedia.com/api/manual-offer/10000/433/ker00sama",
    reward: 160,
    favorite: 0,
  },
  {
    id: 533,
    offer_type: "CPI",
    model: "offer",
    name: "Your-Surveys Router Tier 3",
    instructions: "Complete a survey to earn credits!",
    description: "Your-Surveys router",
    short_description:
      "May be completed an unlimited number of times! Earn credits every time you complete a survey.",
    disclaimer:
      "May be completed an unlimited number of times! Earn credits every time you complete a survey.",
    payout: "0.35",
    image:
      "https://s3.amazonaws.com/adscendmedia-image-storage/5030686-5287454.png",
    countries: [
      "AR",
      "BD",
      "BG",
      "BR",
      "CL",
      "CO",
      "CZ",
      "EG",
      "ES",
      "GR",
      "IL",
      "IT",
      "KG",
      "KZ",
      "MA",
      "MX",
      "NG",
      "PE",
      "PK",
      "RO",
      "RU",
      "SA",
      "TH",
      "TR",
      "UA",
      "VN",
      "ZA",
    ],
    goals: null,
    os: "web",
    incent: "1",
    url: "https://adspiritmedia.com/api/manual-offer/10000/533/ker00sama",
    reward: 175,
    favorite: 0,
  },
  {
    id: 661,
    offer_type: "CPI",
    model: "offer",
    name: "The 7th Grade Math Quiz! - WW - CPA",
    instructions: "Complete a survey and get rewarded",
    description:
      "How well do you remember junior high math? we'll take you back to 7th grade and test your math know-how! Simply finish this math quiz and score 100% at the end to get your reward!",
    short_description:
      "How well do you remember junior high math? we'll take you back to 7th grade and test your math know-how! Simply finish this math quiz and score 100% at the end to get your reward!",
    disclaimer:
      "How well do you remember junior high math? we'll take you back to 7th grade and test your math know-how! Simply finish this math quiz and score 100% at the end to get your reward!",
    payout: "0.10",
    image:
      "https://s3.amazonaws.com/adscendmedia-image-storage/5629466-5738618.png",
    countries: [
      "AP",
      "EU",
      "AD",
      "AF",
      "AG",
      "AI",
      "AL",
      "AM",
      "CW",
      "AO",
      "AQ",
      "AS",
      "AT",
      "AU",
      "AW",
      "AZ",
      "BA",
      "BB",
      "BD",
      "BE",
      "BF",
      "BG",
      "BH",
      "BI",
      "BJ",
      "BM",
      "BN",
      "BO",
      "BR",
      "BS",
      "BT",
      "BV",
      "BW",
      "BZ",
      "CC",
      "CD",
      "CF",
      "CG",
      "CH",
      "CI",
      "CK",
      "CL",
      "CM",
      "CN",
      "CO",
      "CR",
      "CU",
      "CV",
      "CX",
      "CY",
      "CZ",
      "DE",
      "DJ",
      "DK",
      "DM",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "EH",
      "ER",
      "FJ",
      "FK",
      "FM",
      "FO",
      "SX",
      "GA",
      "GB",
      "GD",
      "GE",
      "GF",
      "GI",
      "GL",
      "GM",
      "GN",
      "GP",
      "GQ",
      "GR",
      "GS",
      "GT",
      "GU",
      "GW",
      "GY",
      "HK",
      "HM",
      "HN",
      "HR",
      "HT",
      "HU",
      "IE",
      "IO",
      "IQ",
      "IR",
      "IS",
      "IT",
      "JM",
      "JO",
      "KE",
      "KG",
      "KH",
      "KI",
      "KM",
      "KN",
      "KP",
      "KR",
      "KY",
      "KZ",
      "LA",
      "LB",
      "LC",
      "LI",
      "LK",
      "LR",
      "LS",
      "LT",
      "LU",
      "LV",
      "LY",
      "MA",
      "MC",
      "MD",
      "MG",
      "MH",
      "MK",
      "ML",
      "MM",
      "MN",
      "MO",
      "MP",
      "MQ",
      "MR",
      "MS",
      "MT",
      "MU",
      "MV",
      "MW",
      "MX",
      "MZ",
      "NA",
      "NC",
      "NE",
      "NF",
      "NI",
      "NO",
      "NP",
      "NR",
      "NU",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PF",
      "PG",
      "PH",
      "PL",
      "PM",
      "PN",
      "PR",
      "PS",
      "PT",
      "PW",
      "PY",
      "QA",
      "RE",
      "RO",
      "RW",
      "SA",
      "SB",
      "SC",
      "SD",
      "SE",
      "SG",
      "SH",
      "SI",
      "SJ",
      "SK",
      "SL",
      "SM",
      "SO",
      "ST",
      "SV",
      "SY",
      "SZ",
      "TC",
      "TD",
      "TF",
      "TG",
      "TJ",
      "TK",
      "TM",
      "TN",
      "TO",
      "TL",
      "TR",
      "TT",
      "TV",
      "TW",
      "TZ",
      "UG",
      "UM",
      "US",
      "UY",
      "UZ",
      "VA",
      "VC",
      "VE",
      "VG",
      "VI",
      "VN",
      "VU",
      "WF",
      "WS",
      "XK",
      "YE",
      "YT",
      "RS",
      "ZM",
      "ME",
      "ZW",
      "A1",
      "A2",
      "O1",
      "AX",
      "GG",
      "IM",
      "JE",
      "BL",
      "MF",
      "BQ",
      "SS",
    ],
    goals: null,
    os: "web",
    incent: "1",
    url: "https://adspiritmedia.com/api/manual-offer/10000/661/ker00sama",
    reward: 50,
    favorite: 0,
  },
  {
    id: 1364,
    offer_type: "CPI",
    model: "offer",
    name: "Lumos - VPN to Enjoy Content - iOS - EG - CPI",
    instructions: "Install and Launch to earn reward",
    description:
      "Welcome to VPN Lumos, your ultimate solution for a private and secure online experience. Install and Launch to earn reward",
    short_description:
      "Welcome to VPN Lumos, your ultimate solution for a private and secure online experience. Install and Launch to earn reward",
    disclaimer:
      "Welcome to VPN Lumos, your ultimate solution for a private and secure online experience. Install and Launch to earn reward",
    payout: "0.01",
    image:
      "https://s3.amazonaws.com/adscendmedia-image-storage/5928647-6039528.png",
    countries: ["EG"],
    goals: null,
    os: "ios",
    incent: "0",
    url: "https://adspiritmedia.com/api/manual-offer/10000/1364/ker00sama",
    reward: 5,
    favorite: 0,
  },
  {
    id: 1785173,
    offer_type: "CPI",
    model: "offer",
    name: "Timo Club - Android - EG - CPI",
    instructions: "Install and Launch to earn reward",
    description:
      "Timo club - a new generation social application, where you can play with other people around the city through text, voice, pictures, etc. , and make friends easily. ",
    short_description:
      "Timo club - a new generation social application, where you can play with other people around the city through text, voice, pictures, etc. Install and Launch to earn reward",
    disclaimer:
      "Timo club - a new generation social application, where you can play with other people around the city through text, voice, pictures, etc. Install and Launch to earn reward",
    payout: "0.06",
    image:
      "https://s3.amazonaws.com/adscendmedia-image-storage/5941526-6053199.png",
    countries: ["EG"],
    goals: null,
    os: "android",
    incent: "0",
    url: "https://adspiritmedia.com/api/manual-offer/10000/1785173/ker00sama",
    reward: 30,
    favorite: 0,
  },
];
